import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../../../core/billing/billing_service.dart';
import '../../../core/theme/app_colors.dart';
import '../../../shared_widgets/primary_button.dart';

class PaywallBottomSheet extends StatelessWidget {
  const PaywallBottomSheet({super.key});

  static Future<void> show(BuildContext context) {
    return showModalBottomSheet(
      context: context,
      isScrollControlled: true,
      backgroundColor: Colors.transparent,
      builder: (_) => const PaywallBottomSheet(),
    );
  }

  @override
  Widget build(BuildContext context) {
    final billing = context.watch<BillingService>();

    return Container(
      decoration: const BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.vertical(top: Radius.circular(24)),
      ),
      padding: EdgeInsets.only(
        left: 24,
        right: 24,
        top: 24,
        bottom: MediaQuery.of(context).viewInsets.bottom + 32,
      ),
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          // Handle
          Container(
            width: 40,
            height: 4,
            decoration: BoxDecoration(
              color: AppColors.slate300,
              borderRadius: BorderRadius.circular(2),
            ),
          ),
          const SizedBox(height: 24),

          // Crown Icon
          Container(
            width: 72,
            height: 72,
            decoration: BoxDecoration(
              gradient: const LinearGradient(
                colors: [Color(0xFFF59E0B), Color(0xFFD97706)],
                begin: Alignment.topLeft,
                end: Alignment.bottomRight,
              ),
              borderRadius: BorderRadius.circular(20),
              boxShadow: [
                BoxShadow(
                  color: const Color(0xFFF59E0B).withOpacity(0.3),
                  blurRadius: 16,
                  offset: const Offset(0, 6),
                ),
              ],
            ),
            child: const Icon(Icons.workspace_premium, color: Colors.white, size: 36),
          ),
          const SizedBox(height: 20),

          Text(
            'Unlock Pro Workspace',
            style: Theme.of(context).textTheme.headlineMedium?.copyWith(
                  fontWeight: FontWeight.w800,
                ),
          ),
          const SizedBox(height: 8),
          Text(
            'One-time purchase. No subscriptions. Ever.',
            style: Theme.of(context).textTheme.bodyMedium?.copyWith(
                  color: AppColors.textSecondary,
                ),
            textAlign: TextAlign.center,
          ),
          const SizedBox(height: 28),

          // Features list
          _buildFeatureRow(Icons.hide_image_outlined, 'Remove "Generated by Invoice Maker Pro" watermark'),
          const SizedBox(height: 12),
          _buildFeatureRow(Icons.image_outlined, 'Upload your custom business logo to PDFs'),
          const SizedBox(height: 12),
          _buildFeatureRow(Icons.block, 'Remove all banner & interstitial ads'),
          const SizedBox(height: 12),
          _buildFeatureRow(Icons.all_inclusive, 'Unlimited invoices forever'),
          const SizedBox(height: 32),

          // Price badge
          Container(
            padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 12),
            decoration: BoxDecoration(
              color: AppColors.proGoldLight,
              borderRadius: BorderRadius.circular(12),
              border: Border.all(color: AppColors.proGold.withOpacity(0.3)),
            ),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                Text(
                  '\$4.99',
                  style: Theme.of(context).textTheme.displaySmall?.copyWith(
                        fontWeight: FontWeight.w800,
                        color: AppColors.slate800,
                      ),
                ),
                const SizedBox(width: 8),
                Text(
                  '/ ₹299',
                  style: Theme.of(context).textTheme.titleLarge?.copyWith(
                        color: AppColors.textSecondary,
                      ),
                ),
                const SizedBox(width: 12),
                Container(
                  padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
                  decoration: BoxDecoration(
                    color: AppColors.proGold,
                    borderRadius: BorderRadius.circular(6),
                  ),
                  child: const Text(
                    'ONE-TIME',
                    style: TextStyle(
                      fontSize: 10,
                      fontWeight: FontWeight.w800,
                      color: Colors.white,
                      letterSpacing: 0.5,
                    ),
                  ),
                ),
              ],
            ),
          ),
          const SizedBox(height: 20),

          if (billing.errorMessage != null) ...[
            Text(
              billing.errorMessage!,
              style: const TextStyle(color: AppColors.accentRed, fontSize: 13),
              textAlign: TextAlign.center,
            ),
            const SizedBox(height: 12),
          ],

          PrimaryButton(
            label: 'Unlock Pro – One-Time Purchase',
            isLoading: billing.isLoading,
            onPressed: () => billing.purchasePro(),
            backgroundColor: AppColors.proGold,
          ),
          const SizedBox(height: 12),
          TextButton(
            onPressed: () => billing.restorePurchases(),
            child: Text(
              'Restore Previous Purchase',
              style: TextStyle(color: AppColors.textSecondary, fontSize: 13),
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildFeatureRow(IconData icon, String text) {
    return Row(
      children: [
        Container(
          width: 32,
          height: 32,
          decoration: BoxDecoration(
            color: AppColors.statusPaidBg,
            borderRadius: BorderRadius.circular(8),
          ),
          child: Icon(icon, size: 16, color: AppColors.statusPaid),
        ),
        const SizedBox(width: 12),
        Expanded(
          child: Text(
            text,
            style: const TextStyle(
              fontSize: 14,
              color: AppColors.textPrimary,
              fontWeight: FontWeight.w500,
            ),
          ),
        ),
      ],
    );
  }
}
